'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Devil7.Tools.TallyEasyEntry.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_stock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_stock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;ENVELOPE&gt;
        '''    &lt;HEADER&gt;
        '''        &lt;VERSION&gt;&lt;&lt;version&gt;&gt;&lt;/VERSION&gt;
        '''        &lt;TALLYREQUEST&gt;Export&lt;/TALLYREQUEST&gt;
        '''        &lt;TYPE&gt;Collection&lt;/TYPE&gt;
        '''        &lt;ID&gt;All Masters&lt;/ID&gt;
        '''    &lt;/HEADER&gt;
        '''    &lt;BODY&gt;
        '''        &lt;DESC&gt;
        '''            &lt;TDL&gt;
        '''                &lt;TDLMESSAGE&gt;
        '''                    &lt;COLLECTION NAME=&quot;All Masters&quot; ISMODIFY=&quot;No&quot;&gt;
        '''                        &lt;TYPE&gt;Masters&lt;/TYPE&gt;
        '''                    &lt;/COLLECTION&gt;
        '''                &lt;/TDLMESSAGE&gt;
        '''            &lt;/TDL&gt;
        '''        &lt;/DESC&gt;
        '''     &lt;/BODY&gt;
        '''&lt;/ENVELOPE&gt;.
        '''</summary>
        Friend ReadOnly Property AllMastersRequest() As String
            Get
                Return ResourceManager.GetString("AllMastersRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;ENVELOPE&gt;
        '''&lt;HEADER&gt;
        '''&lt;TALLYREQUEST&gt;Import Data&lt;/TALLYREQUEST&gt;
        '''&lt;/HEADER&gt;
        '''&lt;BODY&gt;
        '''&lt;IMPORTDATA&gt;
        '''&lt;REQUESTDESC&gt;
        '''&lt;REPORTNAME&gt;All Masters&lt;/REPORTNAME&gt;
        '''&lt;STATICVARIABLES&gt;
        '''&lt;SVCURRENTCOMPANY&gt;&lt;&lt;company&gt;&gt;&lt;/SVCURRENTCOMPANY&gt;
        '''&lt;/STATICVARIABLES&gt;
        '''&lt;/REQUESTDESC&gt;
        '''&lt;REQUESTDATA&gt;
        '''&lt;TALLYMESSAGE xmlns:UDF=&quot;TallyUDF&quot;&gt;
        '''&lt;LEDGER NAME=&quot;&lt;&lt;ledger&gt;&gt;&quot; RESERVEDNAME=&quot;&quot;&gt;
        '''&lt;NAME.LIST&gt;
        '''&lt;NAME&gt;&lt;&lt;ledger&gt;&gt;&lt;/NAME&gt;
        '''&lt;/NAME.LIST&gt;
        '''&lt;ADDITIONALNAME&gt;&lt;&lt;ledger&gt;&gt;&lt;/ADDITIONALNAME&gt;
        '''&lt;PARENT&gt;&lt;&lt;group&gt;&gt;&lt;/PARENT&gt;
        '''&lt;ISBILLWISEON&gt;No&lt;/ISBILLWISEON&gt;
        '''&lt;OP [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateLedgerRequest() As String
            Get
                Return ResourceManager.GetString("CreateLedgerRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;ENVELOPE&gt;
        '''&lt;HEADER&gt;
        '''&lt;VERSION&gt;&lt;&lt;version&gt;&gt;&lt;/VERSION&gt;
        '''&lt;TALLYREQUEST&gt;Export&lt;/TALLYREQUEST&gt;
        '''&lt;TYPE&gt;Data&lt;/TYPE&gt;
        '''&lt;ID&gt;&lt;&lt;report&gt;&gt;&lt;/ID&gt;
        '''&lt;/HEADER&gt;
        '''&lt;BODY&gt;
        '''&lt;DESC&gt;
        '''&lt;STATICVARIABLES&gt;
        '''&lt;EXPLODEFLAG&gt;Yes&lt;/EXPLODEFLAG&gt;
        '''&lt;SVEXPORTFORMAT&gt;$$SysName:XML&lt;/SVEXPORTFORMAT&gt;
        '''&lt;/STATICVARIABLES&gt;
        '''&lt;/DESC&gt;
        '''&lt;/BODY&gt;
        '''&lt;/ENVELOPE&gt;.
        '''</summary>
        Friend ReadOnly Property ReportRequest() As String
            Get
                Return ResourceManager.GetString("ReportRequest", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
